CREATE TABLE words (
	id INT(7) UNSIGNED AUTO_INCREMENT,
	word VARCHAR(30) NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE language (
	id INT(7) UNSIGNED AUTO_INCREMENT,
	language VARCHAR(30) NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE pronunciation (
	id INT(7) UNSIGNED AUTO_INCREMENT,
	word_id INT(7) UNSIGNED NOT NULL,
	lang_id INT(7) UNSIGNED NOT NULL,
	ipa VARCHAR(30) NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT fk_word FOREIGN KEY (word_id) REFERENCES words(id),
	CONSTRAINT fk_lang FOREIGN KEY (lang_id) REFERENCES language(id)
);
